-- MySQL Script generated by MySQL Workbench
-- 12/12/16 11:00:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bartdke98_vlambeer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bartdke98_vlambeer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bartdke98_vlambeer` DEFAULT CHARACTER SET utf8 ;
USE `bartdke98_vlambeer` ;

-- -----------------------------------------------------
-- Table `bartdke98_vlambeer`.`TBL_FORUM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bartdke98_vlambeer`.`TBL_FORUM` (
  `forum_id` INT(11) NOT NULL,
  `forum_name` VARCHAR(255) NOT NULL,
  `forum_description` TEXT NOT NULL,
  PRIMARY KEY (`forum_id`),
  UNIQUE INDEX `idTBL_FORUM_UNIQUE` (`forum_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bartdke98_vlambeer`.`TBL_USER_LVL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bartdke98_vlambeer`.`TBL_USER_LVL` (
  `user_lvl_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_lvl_desc` TEXT NOT NULL,
  PRIMARY KEY (`user_lvl_id`),
  UNIQUE INDEX `user_lvl_id_UNIQUE` (`user_lvl_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bartdke98_vlambeer`.`TBL_USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bartdke98_vlambeer`.`TBL_USER` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `profile_picture_path` TEXT NULL,
  `password` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `dob` DATE NOT NULL,
  `phonenumber` VARCHAR(50) NULL,
  `mobilenumber` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `streetname` VARCHAR(50) NOT NULL,
  `housenumber` VARCHAR(10) NOT NULL,
  `zipcode` VARCHAR(12) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `country` VARCHAR(100) NOT NULL,
  `state_or_province` VARCHAR(100) NOT NULL,
  `fk_user_lvl_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_user_lvl_id_idx` (`fk_user_lvl_id` ASC),
  CONSTRAINT `fk_user_lvl_id`
    FOREIGN KEY (`fk_user_lvl_id`)
    REFERENCES `bartdke98_vlambeer`.`TBL_USER_LVL` (`user_lvl_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `bartdke98_vlambeer`.`TBL_THREAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bartdke98_vlambeer`.`TBL_THREAD` (
  `thread_id` INT(11) NOT NULL,
  `thread_subject` VARCHAR(255) NOT NULL,
  `thread_sticky` TINYINT(1) NOT NULL,
  `thread_active` TINYINT(1) NOT NULL,
  `thread_date_created` DATE NOT NULL,
  `fk_user_id` INT(11) NOT NULL,
  `fk_forum_id` INT(11) NOT NULL,
  PRIMARY KEY (`thread_id`),
  UNIQUE INDEX `thread_id_UNIQUE` (`thread_id` ASC),
  INDEX `forum_id_idx` (`fk_forum_id` ASC),
  INDEX `fk_user_id_idx` (`fk_user_id` ASC),
  CONSTRAINT `fk_thread_forum_id`
    FOREIGN KEY (`fk_forum_id`)
    REFERENCES `bartdke98_vlambeer`.`TBL_FORUM` (`forum_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_thread_user_id`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `bartdke98_vlambeer`.`TBL_USER` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bartdke98_vlambeer`.`TBL_POST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bartdke98_vlambeer`.`TBL_POST` (
  `post_id` INT(11) NOT NULL AUTO_INCREMENT,
  `post_subject` VARCHAR(255) NOT NULL,
  `post_message` TEXT NOT NULL,
  `post_upvotes` INT(255) NOT NULL,
  `post_date_created` DATE NOT NULL,
  `fk_thread_id` INT(11) NOT NULL,
  `fk_user_id` INT(11) NOT NULL,
  `reply_id` INT(11) NULL,
  PRIMARY KEY (`post_id`),
  UNIQUE INDEX `post_id_UNIQUE` (`post_id` ASC),
  INDEX `fk_thread_id_idx` (`fk_thread_id` ASC),
  INDEX `reply_id_idx` (`reply_id` ASC),
  INDEX `fk_user_id_idx` (`fk_user_id` ASC),
  CONSTRAINT `fk_post_thread_id`
    FOREIGN KEY (`fk_thread_id`)
    REFERENCES `bartdke98_vlambeer`.`TBL_THREAD` (`thread_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `reply_id`
    FOREIGN KEY (`reply_id`)
    REFERENCES `bartdke98_vlambeer`.`TBL_POST` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_user_id`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `bartdke98_vlambeer`.`TBL_USER` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bartdke98_vlambeer`.`TBL_VAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bartdke98_vlambeer`.`TBL_VAT` (
  `vat_id` INT(11) NOT NULL,
  `vat_percentage` INT(10) NOT NULL,
  PRIMARY KEY (`vat_id`),
  UNIQUE INDEX `vat_id_UNIQUE` (`vat_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bartdke98_vlambeer`.`TBL_BILLING_ADDRESS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bartdke98_vlambeer`.`TBL_BILLING_ADDRESS` (
  `billing_id` INT(11) NOT NULL,
  `billing_firstname` VARCHAR(50) NULL,
  `billing_lastname` VARCHAR(50) NULL,
  `billing_streetname` VARCHAR(50) NULL,
  `billing_housenumber` VARCHAR(10) NULL,
  `billing_zipcode` VARCHAR(12) NULL,
  `billing_city` VARCHAR(100) NULL,
  `billing_country` VARCHAR(100) NULL,
  `billing_state_or_province` VARCHAR(100) NULL,
  PRIMARY KEY (`billing_id`),
  UNIQUE INDEX `billing_id_UNIQUE` (`billing_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bartdke98_vlambeer`.`TBL_PRODUCT_CATEGORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bartdke98_vlambeer`.`TBL_PRODUCT_CATEGORY` (
  `product_cat_id` INT(11) NOT NULL AUTO_INCREMENT,
  `product_cat_desc` TEXT NOT NULL,
  PRIMARY KEY (`product_cat_id`),
  UNIQUE INDEX `product_cat_id_UNIQUE` (`product_cat_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bartdke98_vlambeer`.`TBL_SALE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bartdke98_vlambeer`.`TBL_SALE` (
  `sale_id` INT(11) NOT NULL AUTO_INCREMENT,
  `sale_percentage` INT(100) NOT NULL,
  `sale_image_path` TEXT NOT NULL,
  `sale_date_start` DATE NOT NULL,
  `sale_date_end` DATE NOT NULL,
  `sale_date_add` DATE NOT NULL,
  `sale_is_active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`sale_id`),
  UNIQUE INDEX `sale_id_UNIQUE` (`sale_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bartdke98_vlambeer`.`TBL_PRODUCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bartdke98_vlambeer`.`TBL_PRODUCT` (
  `product_id` INT(11) NOT NULL AUTO_INCREMENT,
  `product_image_path` TEXT NOT NULL,
  `product_description` TEXT NOT NULL,
  `product_date_add` DATE NOT NULL,
  `product_is_active` TINYINT(1) NOT NULL,
  `product_price` INT(100) NOT NULL,
  `product_in_stock` INT(100) NOT NULL,
  `fk_sale_id` INT(11) NULL,
  `fk_product_cat_id` INT(11) NOT NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC),
  INDEX `fk_product_cat_id_idx` (`fk_product_cat_id` ASC),
  INDEX `fk_sale_id_idx` (`fk_sale_id` ASC),
  CONSTRAINT `fk_product_product_cat_id`
    FOREIGN KEY (`fk_product_cat_id`)
    REFERENCES `bartdke98_vlambeer`.`TBL_PRODUCT_CATEGORY` (`product_cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_sale_id`
    FOREIGN KEY (`fk_sale_id`)
    REFERENCES `bartdke98_vlambeer`.`TBL_SALE` (`sale_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bartdke98_vlambeer`.`TBL_ORDER_TO_PRODUCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bartdke98_vlambeer`.`TBL_ORDER_TO_PRODUCT` (
  `quantity` INT(100) NOT NULL,
  `fk_order_id` INT(11) NOT NULL,
  `fk_product_id` INT(11) NOT NULL,
  `pto_id` INT(11) NOT NULL,
  INDEX `fk_product_id_idx` (`fk_product_id` ASC),
  INDEX `fk_order_id_idx` (`fk_order_id` ASC),
  PRIMARY KEY (`pto_id`),
  UNIQUE INDEX `pto_id_UNIQUE` (`fk_product_id` ASC, `fk_order_id` ASC),
  CONSTRAINT `fk_otp_product_id`
    FOREIGN KEY (`fk_product_id`)
    REFERENCES `bartdke98_vlambeer`.`TBL_PRODUCT` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_otp_order_id`
    FOREIGN KEY (`fk_order_id`)
    REFERENCES `bartdke98_vlambeer`.`TBL_ORDER` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bartdke98_vlambeer`.`TBL_ORDER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bartdke98_vlambeer`.`TBL_ORDER` (
  `order_id` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_user_id` INT(11) NOT NULL,
  `fk_vat_id` INT(11) NOT NULL,
  `fk_pto_id` INT(11) NOT NULL,
  `fk_billing_id` INT(11) NULL,
  PRIMARY KEY (`order_id`),
  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC),
  INDEX `fk_user_id_idx` (`fk_user_id` ASC),
  INDEX `fk_vat_id_idx` (`fk_vat_id` ASC),
  INDEX `fk_billing_id_idx` (`fk_billing_id` ASC),
  INDEX `fk_pto_id_idx` (`fk_pto_id` ASC),
  CONSTRAINT `fk_order_user_id`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `bartdke98_vlambeer`.`TBL_USER` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_vat_id`
    FOREIGN KEY (`fk_vat_id`)
    REFERENCES `bartdke98_vlambeer`.`TBL_VAT` (`vat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_billing_id`
    FOREIGN KEY (`fk_billing_id`)
    REFERENCES `bartdke98_vlambeer`.`TBL_BILLING_ADDRESS` (`billing_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_pto_id`
    FOREIGN KEY (`fk_pto_id`)
    REFERENCES `bartdke98_vlambeer`.`TBL_ORDER_TO_PRODUCT` (`pto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bartdke98_vlambeer`.`TBL_INVOICE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bartdke98_vlambeer`.`TBL_INVOICE` (
  `invoice_id` INT(11) NOT NULL AUTO_INCREMENT,
  `invoice_date` DATE NOT NULL,
  `fk_order_id` INT(11) NOT NULL,
  PRIMARY KEY (`invoice_id`),
  UNIQUE INDEX `invoice_id_UNIQUE` (`invoice_id` ASC),
  INDEX `fk_order_id_idx` (`fk_order_id` ASC),
  CONSTRAINT `fk_invoice_order_id`
    FOREIGN KEY (`fk_order_id`)
    REFERENCES `bartdke98_vlambeer`.`TBL_ORDER` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bartdke98_vlambeer`.`TBL_CART_TO_PRODUCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bartdke98_vlambeer`.`TBL_CART_TO_PRODUCT` (
  `ctp_id` INT(11) NOT NULL,
  `fk_shopping_cart_id` INT(11) NOT NULL,
  `fk_product_id` INT(11) NOT NULL,
  `quantity` INT(100) NOT NULL,
  PRIMARY KEY (`ctp_id`),
  UNIQUE INDEX `ctp_id_UNIQUE` (`fk_shopping_cart_id` ASC, `fk_product_id` ASC),
  INDEX `fk_shopping_cart_id_idx` (`fk_shopping_cart_id` ASC),
  INDEX `fk_product_id_idx` (`fk_product_id` ASC),
  CONSTRAINT `fk_ctp_shopping_cart_id`
    FOREIGN KEY (`fk_shopping_cart_id`)
    REFERENCES `bartdke98_vlambeer`.`TBL_SHOPPING_CART` (`shopping_cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ctp_product_id`
    FOREIGN KEY (`fk_product_id`)
    REFERENCES `bartdke98_vlambeer`.`TBL_PRODUCT` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bartdke98_vlambeer`.`TBL_SHOPPING_CART`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bartdke98_vlambeer`.`TBL_SHOPPING_CART` (
  `shopping_cat_id` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_user_id` INT(11) NOT NULL,
  `fk_ctp_id` INT(11) NOT NULL,
  `shopping_cart_date_created` DATE NOT NULL,
  PRIMARY KEY (`shopping_cat_id`),
  UNIQUE INDEX `shopping_cat_id_UNIQUE` (`shopping_cat_id` ASC),
  INDEX `fk_user_id_idx` (`fk_user_id` ASC),
  INDEX `fk_ctp_id_idx` (`fk_ctp_id` ASC),
  CONSTRAINT `fk_shoppingcart_user_id`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `bartdke98_vlambeer`.`TBL_USER` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shoppingcart_ctp_id`
    FOREIGN KEY (`fk_ctp_id`)
    REFERENCES `bartdke98_vlambeer`.`TBL_CART_TO_PRODUCT` (`ctp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
